CREATE TABLE IF NOT EXISTS public.persons
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(100),
    idade integer,
    ip_acesso character varying(100),
    nascimento character varying(255),
    nome character varying(100),
    sexo character varying(30),
    sobre_nome character varying(100),
    CONSTRAINT persons_pkey PRIMARY KEY (id)
);

ALTER TABLE public.persons OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(60) NOT NULL,
    username character varying(100) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE public.users OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.user_role
(
    user_id bigint NOT NULL,
    role integer NOT NULL,
    CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE public.user_role OWNER TO postgres;


INSERT INTO public.users (username, password)
VALUES ('admin', '$2y$12$XWzFZx6j9UZ1z5JHDcZIFeByJgC8XtB1MHXPtQhrM9N/UQx8UwJ/2');

INSERT INTO public.user_role (user_id, role)
SELECT id, 1 FROM public.users WHERE username = 'admin'
